pool:
  vmImage: "ubuntu-latest"

trigger: none

stages:
  - stage: dev
    displayName: "DEV"
    jobs:
    - job: Job_1
      displayName: Remove Network Contributor
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'Data Lake SPN on RG'
        inputs:
          azureSubscription: 'reg-dev-br-project (SPN)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az role assignment delete --role "Network Contributor" --assignee 14dac49d-5f4e-41eb-9694-f997ebd93aa8 --scope /subscriptions/ID/resourceGroups/rg-dev-br-project'

  - stage: sit
    displayName: "SIT"
    jobs:
    - job: Job_1
      displayName: Remove Network Contributor
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'Data Lake SPN on RG'
        inputs:
          azureSubscription: 'reg-dev-br-project (SPN)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az role assignment delete --role "Network Contributor" --assignee 14dac49d-5f4e-41eb-9694-f997ebd93aa8 --scope /subscriptions/ID/resourceGroups/rg-sit-br-project'

  - stage: uat
    displayName: "UAT"
    jobs:
    - job: Job_1
      displayName: Remove Network Contributor
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'Data Lake SPN on RG'
        inputs:
          azureSubscription: 'reg-prd-br-project (SPN)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az role assignment delete --role "Network Contributor" --assignee f4fe8f3f-1485-4497-8946-5aee9735e671 --scope /subscriptions/ID/resourceGroups/rg-uat-br-project'

  - stage: prd
    displayName: "PRD"
    jobs:
    - deployment: GetApprovals
      displayName: "Get Business Owner approval"
      environment: 'project-prd'
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo "Approved"
    - job: Job_1
      displayName: Remove Network Contributor
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'Data Lake SPN on RG'
        inputs:
          azureSubscription: 'reg-prd-br-project (SPN)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az role assignment delete --role "Network Contributor" --assignee f4fe8f3f-1485-4497-8946-5aee9735e671 --scope /subscriptions/ID/resourceGroups/rg-prd-br-project'
