pool:
  vmImage: "ubuntu-latest"

trigger: none

stages:
  - stage: dev
    displayName: "DEV"
    jobs:
    - job: Job_1
      displayName: VNET Subnet DEV
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'VNET Subnet DEV'
        inputs:
          azureSubscription: 'reg-dev-br-project (SPN)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            echo -n "Subnet ID: "
            az network vnet subnet list -g rg-$(System.StageName)-br-project --vnet-name vn-$(System.StageName)-br-project --query "[].[id]" -o tsv

  - stage: sit
    displayName: "SIT"
    jobs:
    - job: Job_1
      displayName: VNET Subnet SIT
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'VNET Subnet SIT'
        inputs:
          azureSubscription: 'reg-dev-br-project (SPN)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            echo -n "VNET ID: "
            az network vnet subnet list -g rg-$(System.StageName)-br-project --vnet-name vn-$(System.StageName)-br-project --query "[].[id]" -o tsv

  - stage: uat
    displayName: "UAT"
    jobs:
    - job: Job_1
      displayName: VNET Subnet UAT
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'VNET Subnet UAT'
        inputs:
          azureSubscription: 'reg-prd-br-project (SPN)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            echo -n "Subnet ID: "
            az network vnet subnet list -g rg-$(System.StageName)-br-project --vnet-name vn-$(System.StageName)-br-project --query "[].[id]" -o tsv

  - stage: prd
    displayName: "PRD"
    jobs:
    - deployment: GetApprovals
      displayName: "Get Business Owner approval"
      environment: 'project-prd'
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo "Approved"
    - job: Job_1
      displayName: VNET Subnet PRD
      steps:
      - checkout: self
      - task: AzureCLI@2
        displayName: 'VNET Subnet PRD'
        inputs:
          azureSubscription: 'reg-prd-br-project (SPN)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            echo -n "Subnet ID: "
            az network vnet subnet list -g rg-$(System.StageName)-br-project --vnet-name vn-$(System.StageName)-br-project --query "[].[id]" -o tsv
